name: ShellCheck CI

on:
  pull_request:
    paths:
      - gh-get-repos
  workflow_dispatch:

jobs:
  check:
    name: Check Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with: 
          additional_files: 'gh-get-repos'
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2155
