name: Extension CI

on:
  pull_request:
    paths:
      - gh-get-repos
  workflow_dispatch:

jobs:
  analyze-extension:
    name: Analyze Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: "gh-get-repos"
        env:
          SHELLCHECK_OPTS: -e SC1091 -e SC2155
  verify-extension:
    name: Verify Extension
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: |
          gh extension install .
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_CI_TOKEN }}
      - name: Verify
        run: |
          gh get-repos --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_CI_TOKEN }}
